---
- name: Get OS specific vars
  include_vars: "{{ item }}"
  loop:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Install fish packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ fish_packages }}"
