---
- name: Get OS specific vars
  include_vars: "{{ ansible_distribution }}.yml"

- include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Install fish packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ fish_packages }}"
