---
- name: Install gpg
  apt:
    name: gnupg
    state: present

- name: Add fish apt key
  apt_key:
    url: "{{ fish_package_repository_key }}"
    state: present

- name: Add fish apt source
  apt_repository:
    repo: "deb {{ fish_package_repository }} /"
    filename: fish
    state: present
  notify:
    - apt update
